### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by ImSummerJohnson**
Hey you guys I'm just learning how everything works,
right now I'm making sure that the description and everything looks alright!

cheers!

### CODE REVIEW

**Comment by dylanhart** [comment]
Don't think that's valid YAML but I'm on my phone so not sure. Did you install Jekyll to test it locally?

**Comment by dylanhart** [comment]
Also is this something we can wait on, because going through the dev branch makes things cleaner.

**Comment by ImSummerJohnson** [comment]
Yeah, I'm going through the github tutorial and I forgot what you told me about going through the different branches.

I'm still kind of feeling things out and I'm still working on understanding everything that I'm doing and looking at.

I realize now that I should have done this in a different branch,
I just wanted to learn how to make your life easier without having to run and ask you for everything.

**Comment by dylanhart** [comment]
Ill make any necessary changes to this later. I'll write up a contributing guide when I'm done with structural changes.

**Pull request merged**
